<a href="https://colab.research.google.com/github/kanishkagarg14/Lecture-1/blob/main/Lectures_of_DAM(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Business Analytics")

Welcome to Business Analytics

In [ ]:
price = 500
quantity = 10

sales = price * quantity

if sales > 4000:
  print("Good Sales")
else:
  print("Low Sales")

Good Sales

In [ ]:
# Number type
# 1. Integer
age = 25
print(age)
print(type(price))

25
<class 'int'>

In [ ]:
# 2. Float
price = 99.50
print(price)
print(type(price))

99.5
<class 'float'>

In [ ]:
# 3. Complex
z = 3 + 4j
print(z)
print(type(z))

(3+4j)
<class 'complex'>

In [ ]:
price = 500
quantity = 10

sales = price // quantity

if sales > 4000:
  print("Good Sales")
else:
  print("Low Sales")
print(type(sales))

Low Sales
<class 'int'>

In [ ]:
price = 500
quantity = 10

sales = price % quantity

if sales > 4000:
  print("Good Sales")
else:
  print("Low Sales")

Low Sales

In [ ]:
price = 500
quantity = 10

sales = price * quantity

if sales == 4000:
  print("Good Sales")
else:
  print("Low Sales")

Low Sales

In [ ]:
price = 500
quantity = 10

sales = price * quantity

if sales != 4000:
  print("Good Sales")
else:
  print("Low Sales")

Good Sales

In [ ]:
#LECTURE 2

In [ ]:
#Byjus Case
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_excel("/content/Lecture2_data.xlsx")

In [ ]:
#Data Description
print(df.head)

<bound method NDFrame.head of    Record_ID         Product       City Quarter  Students_Enrolled  \
0       R001     WhiteHat Jr    Kolkata      Q2                243
1       R002     WhiteHat Jr     Mumbai      Q3                356
2       R003  Aakash Classes    Kolkata      Q3                734
3       R004           Toppr  Bengaluru      Q4                561
4       R005            Osmo  Bengaluru      Q2                331
..       ...             ...        ...     ...                ...
95      R096           Toppr      Delhi      Q4                517
96      R097  Aakash Classes     Mumbai      Q4                937
97      R098     WhiteHat Jr     Mumbai      Q2                371
98      R099  Aakash Classes  Bengaluru      Q1                807
99      R100            Osmo     Mumbai      Q4                414

    Avg_Fee_INR  Discount_Pct  Revenue_Lakh  Marketing_Spend_Lakh  \
0         46500          18.0          92.7                 247.0
1         44000          21.5         123.2                 353.1
2         93200          15.9         575.7                 114.6
3         19500          18.5          89.3                 153.7
4         12200          14.2          34.8                  82.6
..          ...           ...           ...                   ...
95        19700          20.8          80.7                 172.0
96        85300          21.6         626.6                 182.3
97        43200          17.3         132.8                 335.6
98        88100           9.6         643.0                 130.7
99        12100          20.7          39.8                 102.1

    Content_Cost_Lakh  Salary_Cost_Lakh  Other_Cost_Lakh  Sales_Team_Size  \
0                49.9             109.2             39.2               20
1                71.3             105.8             40.6               33
2                88.1             203.9             90.4               17
3                67.4              80.7             34.3               17
4                41.1              48.5             16.3               11
..                ...               ...              ...              ...
95               62.5              72.9             29.0               19
96              133.9             210.7            111.4               27
97               67.8             101.7             41.7               31
98              112.0             185.4             97.1               22
99               48.0              48.2             22.1               12

    Refund_Pct  Customer_Rating
0          8.4              3.9
1          7.4              4.0
2          4.7              4.3
3          8.3              3.7
4          3.2              4.2
..         ...              ...
95         9.4              3.8
96         7.9              4.0
97         6.2              3.9
98         3.9              4.3
99         7.2              4.4

[100 rows x 15 columns]>

In [ ]:
print (df.shape)

(100, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Record_ID             100 non-null    object
 1   Product               100 non-null    object
 2   City                  100 non-null    object
 3   Quarter               100 non-null    object
 4   Students_Enrolled     100 non-null    int64
 5   Avg_Fee_INR           100 non-null    int64
 6   Discount_Pct          100 non-null    float64
 7   Revenue_Lakh          100 non-null    float64
 8   Marketing_Spend_Lakh  100 non-null    float64
 9   Content_Cost_Lakh     100 non-null    float64
 10  Salary_Cost_Lakh      100 non-null    float64
 11  Other_Cost_Lakh       100 non-null    float64
 12  Sales_Team_Size       100 non-null    int64
 13  Refund_Pct            100 non-null    float64
 14  Customer_Rating       96 non-null     float64
dtypes: float64(8), int64(3), object(4)
memory usage: 11.8+ KB

In [ ]:
print (df.dtypes)

Record_ID                object
Product                  object
City                     object
Quarter                  object
Students_Enrolled         int64
Avg_Fee_INR               int64
Discount_Pct            float64
Revenue_Lakh            float64
Marketing_Spend_Lakh    float64
Content_Cost_Lakh       float64
Salary_Cost_Lakh        float64
Other_Cost_Lakh         float64
Sales_Team_Size           int64
Refund_Pct              float64
Customer_Rating         float64
dtype: object

In [ ]:
# Top 10 profit/loss product
df["Total_Cost_Lakh"]=(df["Marketing_Spend_Lakh"]+df["Content_Cost_Lakh"]+df["Salary_Cost_Lakh"]+df["Other_Cost_Lakh"])

In [ ]:
df["Profit_Lakh"]=df["Revenue_Lakh"]-df["Total_Cost_Lakh"]
print(df[["Product","Revenue_Lakh","Total_Cost_Lakh","Profit_Lakh"]].head(10))

          Product  Revenue_Lakh  Total_Cost_Lakh  Profit_Lakh
0     WhiteHat Jr          92.7            445.3       -352.6
1     WhiteHat Jr         123.2            570.8       -447.6
2  Aakash Classes         575.7            497.0         78.7
3           Toppr          89.3            336.1       -246.8
4            Osmo          34.8            188.5       -153.7
5    Learning App         228.7            521.1       -292.4
6           Toppr          87.4            276.9       -189.5
7  Aakash Classes         595.5            554.9         40.6
8           Toppr          94.4            307.7       -213.3
9     WhiteHat Jr         114.8            566.5       -451.7

In [ ]:
#Missing Value
#isna=is not available
print(df.isna().sum())

Record_ID               0
Product                 0
City                    0
Quarter                 0
Students_Enrolled       0
Avg_Fee_INR             0
Discount_Pct            0
Revenue_Lakh            0
Marketing_Spend_Lakh    0
Content_Cost_Lakh       0
Salary_Cost_Lakh        0
Other_Cost_Lakh         0
Sales_Team_Size         0
Refund_Pct              0
Customer_Rating         4
Total_Cost_Lakh         0
Profit_Lakh             0
dtype: int64

In [ ]:
# Decision making structure
#If Statements
rating=df["Customer_Rating"].mean()

if rating>=4:
  print("Customer satisfaction is good")

Customer satisfaction is good

In [ ]:
rating=df["Revenue_Lakh"].mean()

if rating>=200:
  print("Company is good")

Company is good

In [ ]:
#Decision making structure
#if else
revenue=df["Revenue_Lakh"].mean()

if revenue >=300:
  print("Average revenue is high")
else:
  print("Average revenue is low")

Average revenue is low

In [ ]:
#Lecture 3

In [ ]:
#Lecture 4

In [ ]:
#Starbucks Case
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_excel("/content/Starbucks_India_Sales_Dataset.xlsx")

In [ ]:
#Data Discription
print (df.head)

<bound method NDFrame.head of     OrderID       Date       City StoreID           Product     Category  \
0   SBX1001 2026-07-01  Hyderabad     S07        Cappuccino   Hot Coffee
1   SBX1002 2026-07-01  Bengaluru     S05         Cold Brew  Cold Coffee
2   SBX1003 2026-07-01     Mumbai     S03        Cappuccino   Hot Coffee
3   SBX1004 2026-07-02  Hyderabad     S08  Blueberry Muffin         Food
4   SBX1005 2026-07-04      Delhi     S01             Latte   Hot Coffee
..      ...        ...        ...     ...               ...          ...
95  SBX1096 2026-09-28     Mumbai     S04         Americano   Hot Coffee
96  SBX1097 2026-09-28  Bengaluru     S05        Cappuccino   Hot Coffee
97  SBX1098 2026-09-28       Pune     S10       Frappuccino  Cold Coffee
98  SBX1099 2026-09-29  Bengaluru     S06             Latte   Hot Coffee
99  SBX1100 2026-09-30     Mumbai     S03       Frappuccino  Cold Coffee

       Size  Unit_Price  Quantity  Discount_Pct  Revenue Payment_Mode  \
0    Grande         280         1          0.00    280.0          UPI
1      Tall         300         1          0.10    270.0          UPI
2     Venti         310         1          0.05    294.5          UPI
3   Regular         180         1          0.20    144.0       Wallet
4    Grande         300         2          0.20    480.0         Card
..      ...         ...       ...           ...      ...          ...
95     Tall         220         2          0.00    440.0         Cash
96     Tall         250         3          0.00    750.0         Card
97   Grande         380         1          0.00    380.0         Card
98    Venti         330         3          0.00    990.0          UPI
99    Venti         410         2          0.00    820.0          UPI

   Customer_Type Order_Channel  Rating
0            New      In-store     4.0
1         Member      In-store     4.0
2      Returning      In-store     2.0
3         Member      In-store     3.0
4         Member      In-store     4.0
..           ...           ...     ...
95        Member      In-store     5.0
96     Returning      Delivery     4.0
97           New      In-store     3.0
98           New      In-store     4.0
99     Returning      In-store     NaN

[100 rows x 15 columns]>

In [ ]:
print (df.shape)

(100, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        100 non-null    object
 1   Date           100 non-null    datetime64[ns]
 2   City           100 non-null    object
 3   StoreID        100 non-null    object
 4   Product        100 non-null    object
 5   Category       100 non-null    object
 6   Size           100 non-null    object
 7   Unit_Price     100 non-null    int64
 8   Quantity       100 non-null    int64
 9   Discount_Pct   100 non-null    float64
 10  Revenue        100 non-null    float64
 11  Payment_Mode   100 non-null    object
 12  Customer_Type  100 non-null    object
 13  Order_Channel  100 non-null    object
 14  Rating         97 non-null     float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(9)
memory usage: 11.8+ KB

In [ ]:
print (df.dtypes)

OrderID                  object
Date             datetime64[ns]
City                     object
StoreID                  object
Product                  object
Category                 object
Size                     object
Unit_Price                int64
Quantity                  int64
Discount_Pct            float64
Revenue                 float64
Payment_Mode             object
Customer_Type            object
Order_Channel            object
Rating                  float64
dtype: object

In [ ]:
import pandas as pd
#Excel file path
FILE="/content/Starbucks_India_Sales_Dataset.xlsx"

#load the Excel sheets
df= pd.read_excel(FILE, sheet_name="Sales_Data")
products_df = pd.read_excel (FILE, sheet_name="Products")
stores_df = pd.read_excel (FILE, sheet_name="Stores")

# Check the data
print("Sales table:", df.shape)
print("Products:", products_df.shape)
print("Stores:", stores_df.shape)

#Display first 5 rows
df.head()

Sales table: (100, 15)
Products: (8, 4)
Stores: (10, 5)

,OrderID,Date,City,StoreID,Product,Category,Size,Unit_Price,Quantity,Discount_Pct,Revenue,Payment_Mode,Customer_Type,Order_Channel,Rating
0,SBX1001,2026-07-01,Hyderabad,S07,Cappuccino,Hot Coffee,Grande,280,1,0.00,280.0,UPI,New,In-store,4.0
1,SBX1002,2026-07-01,Bengaluru,S05,Cold Brew,Cold Coffee,Tall,300,1,0.10,270.0,UPI,Member,In-store,4.0
2,SBX1003,2026-07-01,Mumbai,S03,Cappuccino,Hot Coffee,Venti,310,1,0.05,294.5,UPI,Returning,In-store,2.0
3,SBX1004,2026-07-02,Hyderabad,S08,Blueberry Muffin,Food,Regular,180,1,0.20,144.0,Wallet,Member,In-store,3.0
4,SBX1005,2026-07-04,Delhi,S01,Latte,Hot Coffee,Grande,300,2,0.20,480.0,Card,Member,In-store,4.0

In [ ]:
#---- Part A: Create by typing----

#LIST: the starbucks menu (8 products)
menu = ["Cappuccino", "Latte", "Americano", "Cold Brew", "Frappuccino", "Masala Chai", "Blueberry Muffin", "Veg Sandwich"]

#TUPLE: one store's fixed details(StoreID, name, city)
store = ("S01", "Connaught Place", "Delhi")

#SET: cities where starbucks sells (the duplicate 'Delhi' is removed automatically)
cities= {"Delhi","Mumbai", "Bengaluru", "Hyderabad", "Pune", "Delhi"}

#DICTIONART: product -> base price in Rs
price={"cappuccino": 250, "Latte": 270, "Americano": 220, "Cold Brew": 300, "Frappuccino": 350, "Masala Chai": 200, "Blueberry Muffin": 180, "Veg Sandwich": 240}

print("List :", menu)
print("Tuple:", store)
print("Set:", cities, "<- 'Delhi' typed twice, stored once")
print("Dictionary:", price)
print()
print(type(menu), type(store), type(cities), type(price))

List : ['Cappuccino', 'Latte', 'Americano', 'Cold Brew', 'Frappuccino', 'Masala Chai', 'Blueberry Muffin', 'Veg Sandwich']
Tuple: ('S01', 'Connaught Place', 'Delhi')
Set: {'Mumbai', 'Hyderabad', 'Bengaluru', 'Delhi', 'Pune'} <- 'Delhi' typed twice, stored once
Dictionary: {'cappuccino': 250, 'Latte': 270, 'Americano': 220, 'Cold Brew': 300, 'Frappuccino': 350, 'Masala Chai': 200, 'Blueberry Muffin': 180, 'Veg Sandwich': 240}

<class 'list'> <class 'tuple'> <class 'set'> <class 'dict'>

In [ ]:
#---- Part B: create them from the Excel data----
# Each Excel column becomes a Python list. Each Excel row becomes a dictionary.

product_list = df["Product"].tolist()        # 100 products (with repeats)
city_list    = df["City"].tolist()           # 100 cities  (with repeats)
qty_list     = df["Quantity"].tolist()       # 100 quantities
revenue_list = df["Revenue"].tolist()        # 100 revenue values

first_order   = df.iloc[0].to_dict()                 # ONE order  -> dictionary
first_5_orders = df.head(5).to_dict("records")       # FIVE orders -> list of dictionaries

print("Items in product_list :", len(product_list))
print("Unique cities (set)   :", set(city_list))
print()
print("First order as a dictionary:")
print(first_order)

Items in product_list : 100
Unique cities (set)   : {'Mumbai', 'Hyderabad', 'Bengaluru', 'Delhi', 'Pune'}

First order as a dictionary:
{'OrderID': 'SBX1001', 'Date': Timestamp('2026-07-01 00:00:00'), 'City': 'Hyderabad', 'StoreID': 'S07', 'Product': 'Cappuccino', 'Category': 'Hot Coffee', 'Size': 'Grande', 'Unit_Price': 280, 'Quantity': 1, 'Discount_Pct': 0.0, 'Revenue': 280.0, 'Payment_Mode': 'UPI', 'Customer_Type': 'New', 'Order_Channel': 'In-store', 'Rating': 4.0}

In [ ]:
# --- List ---
print("First item      :", menu[0])
print("Last item       :", menu[-1])
print("First three     :", menu[0:3])      # slicing: start included, end excluded
print("Every 2nd item  :", menu[::2])

# --- Tuple (same as list) ---
print("\nStore ID        :", store[0])
print("Store city      :", store[2])

# --- Dictionary ---
print("\nPrice of Latte  :", price["Latte"])
print("Safe lookup     :", price.get("Pizza", "Not on menu"))   # no error if key is missing

# --- Set ---
print("\nIs Pune a Starbucks city?   ", "Pune" in cities)
print("Is Jaipur a Starbucks city? ", "Jaipur" in cities)

First item      : Cappuccino
Last item       : Veg Sandwich
First three     : ['Cappuccino', 'Latte', 'Americano']
Every 2nd item  : ['Cappuccino', 'Americano', 'Frappuccino', 'Blueberry Muffin']

Store ID        : S01
Store city      : Delhi

Price of Latte  : 270
Safe lookup     : Not on menu

Is Pune a Starbucks city?    True
Is Jaipur a Starbucks city?  False

In [ ]:
# --- Changing data: a list is changeable, a tuple is not ---
menu[6] = "Muffin"
print("Updated menu :", menu)
menu[6] = "Blueberry Muffin"          # change it back, we need the original name later

try:
    store[1] = "Saket Mall"
except TypeError as e:
    print("Tuple error  :", e)

Updated menu : ['Cappuccino', 'Latte', 'Americano', 'Cold Brew', 'Frappuccino', 'Masala Chai', 'Muffin', 'Veg Sandwich']
Tuple error  : 'tuple' object does not support item assignment

In [ ]:
# --- Access the real Excel data stored in Python structures ---
print("City of order #1       :", city_list[0])
print("Quantity of last order :", qty_list[-1])
print("First 5 revenues       :", revenue_list[:5])

print("\nProduct of first order :", first_order["Product"])
print("Revenue of first order :", first_order["Revenue"])

# list of dictionaries: [position][key]
print("\nCity of 3rd order      :", first_5_orders[2]["City"])
print("Product of 3rd order   :", first_5_orders[2]["Product"])

City of order #1       : Hyderabad
Quantity of last order : 2
First 5 revenues       : [280.0, 270.0, 294.5, 144.0, 480.0]

Product of first order : Cappuccino
Revenue of first order : 280.0

City of 3rd order      : Mumbai
Product of 3rd order   : Cappuccino

In [ ]:
# Built-in functions on the Revenue list (100 orders)
print("Number of orders   :", len(revenue_list))
print("Total revenue      : Rs", round(sum(revenue_list), 2))
print("Average order value: Rs", round(sum(revenue_list) / len(revenue_list), 2))
print("Biggest order      : Rs", max(revenue_list))
print("Smallest order     : Rs", min(revenue_list))
print("Top 5 orders       :", sorted(revenue_list, reverse=True)[:5])
print("Total cups/items   :", sum(qty_list))

Number of orders   : 100
Total revenue      : Rs 43652.5
Average order value: Rs 436.52
Biggest order      : Rs 2050.0
Smallest order     : Rs 144.0
Top 5 orders       : [2050.0, 1282.5, 990.0, 930.0, 900.0]
Total cups/items   : 173

In [3]:
#LECTURE 5 : descriptive statistics/ data visualisation

In [3]:
# !pip install seaborn plotly openpyx1      # only if a library is missing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df=pd.read_excel("/content/Zomato_India_Orders_Dataset.xlsx", sheet_name="Orders_Data")
print ("Data loaded:", df.shape[0], "orders and", df.shape[1], "Variables")

Data loaded: 200 orders and 15 Variables

In [4]:
# About the data set/ attributes
# 1. Shape: tells us the number of rows and columns
print("shape:", df.shape)

# 2. Column: shows the name of all columns
print("/columns:")
print(df.columns)

# 3. Index: shows the row labels
print("/nIndex:")
print(df.index)

# 4. Data Types: tells us the type of data in each column
print("/nData Types:")
print(df.dtypes)

shape: (200, 15)
/columns:
Index(['Order_ID', 'Order_Date', 'City', 'Cuisine', 'Customer_Segment',
       'Platform', 'Items_Count', 'Order_Value', 'Discount_Pct',
       'Delivery_Fee', 'Payment_Mode', 'Distance_Km', 'Delivery_Time_Min',
       'Rating', 'Final_Amount'],
      dtype='object')
/nIndex:
RangeIndex(start=0, stop=200, step=1)
/nData Types:
Order_ID                     object
Order_Date           datetime64[ns]
City                         object
Cuisine                      object
Customer_Segment             object
Platform                     object
Items_Count                   int64
Order_Value                   int64
Discount_Pct                float64
Delivery_Fee                  int64
Payment_Mode                 object
Distance_Km                 float64
Delivery_Time_Min             int64
Rating                      float64
Final_Amount                float64
dtype: object

Classification

In [5]:
# 1.5 Classify the variables (we decide this using the data dictionary)
number_cols = ["Items_Count", "Order_Value", "Discount_Pct", "Delivery_Fee","Distance_Km", "Delivery_Time_Min","Rating","Final_Amount"]
category_cols= ["City", "Cuisine", "Customer_Segment", "Platform", "Payment_Mode"]
date_cols = ["Order_Date"]
id_cols = ["Order_ID"]

print("Numerical:", len(number_cols), number_cols)
print("Categorical:", len(category_cols), category_cols)
print("Data:", date_cols)
print ("ID:", id_cols)

Numerical: 8 ['Items_Count', 'Order_Value', 'Discount_Pct', 'Delivery_Fee', 'Distance_Km', 'Delivery_Time_Min', 'Rating', 'Final_Amount']
Categorical: 5 ['City', 'Cuisine', 'Customer_Segment', 'Platform', 'Payment_Mode']
Data: ['Order_Date']
ID: ['Order_ID']

Find missing values

In [6]:
# 1.6 DAta quality check: missing values and duplictes
print("Missing values in each column:")
print(df.isnull().sum())

print("/nColumns with missing data:")
missing= df.isnull().sum()
print(missing[missing > 0])
print("Percent missing in Rating:", round(df["Rating"].isnull().mean() * 100,1), "%")

print("/nDuplicate rows:", df.duplicated().sum())
print("Is Order_ID unique?:", df["Order_ID"].is_unique)

Missing values in each column:
Order_ID             0
Order_Date           0
City                 0
Cuisine              0
Customer_Segment     0
Platform             0
Items_Count          0
Order_Value          0
Discount_Pct         0
Delivery_Fee         0
Payment_Mode         0
Distance_Km          0
Delivery_Time_Min    0
Rating               8
Final_Amount         0
dtype: int64
/nColumns with missing data:
Rating    8
dtype: int64
Percent missing in Rating: 4.0 %
/nDuplicate rows: 0
Is Order_ID unique?: True

#Descriptive Statistics

In [7]:
df.describe()

,Order_Date,Items_Count,Order_Value,Discount_Pct,Delivery_Fee,Distance_Km,Delivery_Time_Min,Rating,Final_Amount
count,200,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,192.000000,200.000000
mean,2026-08-22 04:26:24,2.770000,649.200000,0.086000,14.150000,6.459500,39.210000,4.031250,606.597500
min,2026-07-01 00:00:00,1.000000,120.000000,0.000000,0.000000,0.500000,11.000000,1.000000,119.000000
25%,2026-07-30 18:00:00,2.000000,310.000000,0.000000,0.000000,3.275000,28.750000,3.000000,309.000000
50%,2026-08-28 12:00:00,3.000000,545.000000,0.100000,0.000000,6.600000,39.000000,4.000000,499.500000
75%,2026-09-14 00:00:00,4.000000,830.000000,0.100000,30.000000,9.700000,49.000000,5.000000,724.000000
max,2026-09-30 00:00:00,6.000000,4850.000000,0.200000,50.000000,12.000000,112.000000,5.000000,4365.000000
std,NaN,1.475801,510.676328,0.069304,19.107669,3.496532,13.816671,0.891532,460.690171

In [8]:
# 2.1 describe(): one command, many statistics (numerical columns)
df [number_cols].describe().round(2)

,Items_Count,Order_Value,Discount_Pct,Delivery_Fee,Distance_Km,Delivery_Time_Min,Rating,Final_Amount
count,200.00,200.00,200.00,200.00,200.00,200.00,192.00,200.00
mean,2.77,649.20,0.09,14.15,6.46,39.21,4.03,606.60
std,1.48,510.68,0.07,19.11,3.50,13.82,0.89,460.69
min,1.00,120.00,0.00,0.00,0.50,11.00,1.00,119.00
25%,2.00,310.00,0.00,0.00,3.28,28.75,3.00,309.00
50%,3.00,545.00,0.10,0.00,6.60,39.00,4.00,499.50
75%,4.00,830.00,0.10,30.00,9.70,49.00,5.00,724.00
max,6.00,4850.00,0.20,50.00,12.00,112.00,5.00,4365.00

In [9]:
# 2.2 Statistics for one important column: final_amount (what the customer pay )
amount = df["Final_Amount"]

print("Mean(average):Rs", round(amount.mean(),2))
print("Median(middle):Rs", amount.median())
print("Mode(most common):Rs", amount.mode()[0])
print("Maximum: Rs", amount.max())
print("Minimum: Rs", amount.min())
print("Standard deviation: Rs",round(amount.std(), 2))
print("Range(max-min): Rs", amount.max() - amount.min())

Mean(average):Rs 606.6
Median(middle):Rs 499.5
Mode(most common):Rs 410.0
Maximum: Rs 4365.0
Minimum: Rs 119.0
Standard deviation: Rs 460.69
Range(max-min): Rs 4246.0